name: "gdp-deploy-publish"
description: "gdp-deploy-publish"
inputs:
  github_token:
    required: true
    description: "github token"

runs:
  using: "composite"
  steps:
    - name: SetupGo
      uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - name: SetupHub
      shell: bash
      run: |
        sudo apt install hub
        touch ~/.config/hub
    - name: SetupGdp
      shell: bash
      run: go install github.com/Connehito/gdp@latest
    - name: GdpDeploy
      shell: bash
      run: echo yes | gdp deploy -f
      env:
        TZ: 'Asia/Tokyo'
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: GdpPublish
      shell: bash
      run: gdp publish
      env:
        TZ: 'Asia/Tokyo'
        GITHUB_TOKEN: ${{ inputs.github_token }}
