name: Release
on:
  push:
    branches:
      - main

jobs:
  yarn-install:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: yarn
        run: |
          yarn install
          yarn run tsc
      - name: gdp-deploy-publish
        uses: ./.github/actions/gdp-deploy-publish
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
