name: test
on:
  pull_request # types: opened, synchronize, and reopened by default

jobs:
  tslint:
    name: tslint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: yarn run tslint
        run: |
          yarn install
          yarn run tslint 'src/**/*.ts'

  diff-dist-index:
    name: diff-dist-index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: DiffIndex
        shell: bash
        run: |
          yarn install
          yarn run tsc --outDir ./tmp
          diff ./dist/index.js ./tmp/index.js
